name: Compile Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Compile backend code
      run: |
        pyinstaller --onefile backend/main.py --add-data 'frontend/build;frontend/build'

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-backend
        path: dist/main.exe
